#pragma once

typedef enum
{
    GW_STATE_BOOT = 0,
    GW_STATE_NO_INTERNET,

    GW_STATE_ETH_CONNECTING,
    GW_STATE_ETH_ONLINE,

    GW_STATE_WIFI_CONNECTING,
    GW_STATE_WIFI_ONLINE,
    GW_STATE_AP_MODE,

    GW_STATE_MQTT_CONNECTING,
    GW_STATE_MQTT_CONNECTED,

    GW_STATE_SENDING_DATA,
} gateway_state_t;
